### PR TITLE
Graceful publishing of stats

### LINKED ISSUE #40: Iterations panic when one of the lighthouse categories has empty score
Lighthouse so happens to sometimes return empty values for some runs. This often happens for non-PWA websites when pwa is always empty.

```
Error: Tried to add null to stats for path pwa
    at Object.pushStats (/usr/src/app/lib/support/statsHelpers.js:27:13)
    at /lighthouse/aggregator.js:15:25
    at /lighthouse/node_modules/lodash.foreach/index.js:221:11
    at baseForOwn (/lighthouse/node_modules/lodash.foreach/index.js:153:20)
    at /lighthouse/node_modules/lodash.foreach/index.js:190:14
    at forEach (/lighthouse/node_modules/lodash.foreach/index.js:290:10)
    at Aggregator.addToAggregate (/lighthouse/aggregator.js:14:5)
    at Object.processMessage (/lighthouse/index.js:155:29)
```

We've also seen this error for other categories as well randomly, and frequency of these errors increases as we increase the number of iterations.

### PR DESCRIPTION
**Pull request by rdsubhas**
* Fixes #40 – more info about the underlying issue in #40 
* Gracefully publish stats for each iteration
* If some categories are empty, skip and continue to next iteration
* This especially happens with non-PWA websites
* On one hand, it may sound like a hard fail is good. But on the other hand, since we have multiple iterations, these cases always happen for one page or the other and it's annoying to have the whole sitespeed build fail just due to one iteration. We users are fine and we even expect one or two iterations to fail, since we have multiple iterations as a fallback
* Debated whether we should publish zero score, or skip and continue. If we publish zero score, it would skew the metrics towards zero, hence skipping that one stat and continuing to next iteration

### CODE REVIEW

**Comment by rdsubhas** [comment]
cc @soulgalore

**Comment by soulgalore** [comment]
Yeah I saw it but been busy all day, sorry. Hopefully I can have a look tonight in about 3 hours or so.

File: aggregator.js [hunk 1]
```diff
@@ -10,30 +10,26 @@ class Aggregator {
     this.stats = {};
   }
 
+  _pushStats(path, value) {
+    if (!(value > 0)) {
```
Comment (soulgalore) [inline aggregator.js]: We should use 0 since else it would skewed right? Since we can do multiple runs now and you could get different result depending on what you get back, skipping 0 would skew it more than not skipping. Or how do you think? :)

Comment (soulgalore) [reply aggregator.js]: I'll fix this after, so we can push this in the coming fix release.
